version: "2"

services:
  postgis:
    container_name: pg-gh-postgis
    build: .
    ports:
      - "8432:5432"
    networks:
      - pg-graphhopper
    environment:
      GH_API_URL: "http://graphhopper:8989"

  graphhopper:
    container_name: pg-gh-graphhopper
    # image: graphhopper/graphhopper
    image: crazycapivara/graphhopper:ext_pointlist
    ports:
      - "9090:8989"
    networks:
      - pg-graphhopper

networks:
  pg-graphhopper:
    driver: bridge

